# Generated by Django 5.2.6 on 2025-09-23 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='waitlistentry',
            name='company',
        ),
        migrations.AddField(
            model_name='waitlistentry',
            name='country_code',
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AddField(
            model_name='waitlistentry',
            name='phone_number',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
